version: "3.9"

services:
  nodejs:
    hostname: nodejs-bb453a
    image: node_mmpi2
    build: .
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://127.0.0.1:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
    #    volumes:
    #      - ./app:/app
    networks:
      - proxynet
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.10"
          memory: 100M
      restart_policy:
        condition: on-failure
        delay: 4s
        max_attempts: 10
        window: 10s
      update_config:
        parallelism: 2
        delay: 10s
        order: start-first

networks:
  proxynet:
    external: true
