// MMPI-2 Questions

var questions = [
	// 0 - Description
	"MMPI-2 Questions",
	// 1
	"Gosto de revistas de mecânica.",
	// 2
	"Tenho bom apetite.",
	// 3...
	"Levanto-me de manhã quase sempre \"fresco/a\" e descansado/a.",
	"Acho que gostaria de trabalhar como bibliotecário/a.",
	" Acordo facilmente com o barulho.",
	"O meu pai é um bom homem ou (se já faleceu) o meu pai foi um bom homem.",
	"Gosto de ler artigos dos jornais sobre crimes.",
	"Normalmente tenho os pés e as mãos suficientemente quentes.",
	"Na minha vida diária existem muitas coisas que me interessam.",
	"Atualmente tenho tanta capacidade para trabalhar como antes.",
	"Na maior parte do tempo parece que tenho um nó na garganta.",
	"A minha vida sexual é satisfatória.",
	"As pessoas deveriam tentar compreender os seus sonhos e guiar-se por eles ou tê-los como um aviso.",
	"As histórias de detetives e de mistério divertem-me.",
	"Trabalho sob uma tensão muito grande.",
	"De vez em quando penso em coisas demasiado indecentes para poder falar nelas.",
	"Estou certo de que a vida é dura para mim.",
	"Sofro de náuseas e vómitos.",
	"Quando aceito um novo emprego gosto de saber com quem é importante ser agradável.",
	"Raramente estou indisposto/a.",
	"Há alturas em que tenho desejado muitíssimo abandonar a minha casa.",
	"Ninguém parece compreender-me.",
	"Por vezes tenho ataques de riso ou choro que não consigo controlar.",
	"Por vezes estou possuído/a por espíritos diabólicos.",
	"Gostaria de ser cantor/a.",
	"Quando estou em dificuldades ou problemas o melhor é calar-me.",
	"Quando alguém me faz mal sinto que se puder devo pagar-lhe na mesma moeda, apenas por uma questão de princípio.",
	"Sinto-me mal do estômago várias vezes por semana.",
	"Às vezes apetece-me praguejar.",
	"Frequentemente tenho pesadelos durante a noite.",
	"Custa-me bastante concentrar-me numa tarefa ou num trabalho.",
	"Já passei por experiências muito peculiares e estranhas.",
	"Raramente me preocupo com a minha saúde.",
	"Nunca tive problemas por causa do meu comportamento sexual.",
	"Quando era jovem houve ocasiões em que roubei algumas coisas.",
	"Quase sempre tenho tosse.",
	"Às vezes tenho vontade de partir coisas.",
	"Tive períodos de dias, semanas ou meses em que não conseguia preocupar-me com as coisas porque não tinha ânimo para nada",
	"O meu sono é irregular e intranquilo.",
	"A maior parte do tempo parece que me dói a cabeça toda.",
	"Não digo sempre a verdade.",
	"Se os outros não me quisessem mal eu teria tido muito mais sucesso.",
	"O meu raciocínio está agora melhor do que nunca.",
	"Uma vez por semana ou mais frequentemente sinto calor por todo o corpo sem causa aparente.",
	"Tenho uma saúde física tão boa como a maior parte dos meus amigos.",
	"Prefiro passar-me por despercebido com os amigos da escola ou com pessoas conhecidas que não vejo há muito tempo, a não ser que falem primeiro comigo.",
	"Quase nunca me dói o peito ou o coração.",
	"Em diversas ocasiões gostaria de me sentar e sonhar acordado / a do que fazer qualquer outra coisa.",
	"Sou uma pessoa muito sociável.",
	"Tive de receber frequentemente ordens de pessoas que sabiam menos do que eu.",
	"Não leio todos os dias o editorial do jornal.",
	"Não tenho levado um tipo de vida adequado e normal.",
	"Frequentemente parece que sinto ardores, picadas, formigueiro ou dormência em algumas partes do corpo.",
	"A minha família não gosta do trabalho que escolhi(ou o trabalho que penso escolher para o meu futuro).",
	"Às vezes insisto tanto numa coisa que os outros acabam por perder a paciência comigo.",
	"Gostaria de ser tão feliz como os outros parecem ser.",
	"Raramente sinto dores na nuca.",
	"Penso que a grande maioria das pessoas exagera as suas desgraças para conquistar a simpatia e a ajuda dos outros.",
	"Sinto um mal-estar no estômago quase todos os dias.",
	"Quando estou com pessoas incomoda-me ouvir coisas muito estranhas.",
	"Sou uma pessoa importante.",
	" Desejo frequentemente ser mulher (ou se você é mulher) nunca me incomodou ser mulher.",
	"Os meus sentimentos não são facilmente feridos.",
	"Gosto de ler histórias de amor.",
	"Sinto-me triste a maior parte do tempo.",
	"Seria melhor se quase todas as leis fossem abolidas.",
	"Gosto de poesia.",
	"Às vezes arrelio os animais.",
	"Acho que gostaria de trabalhar como guarda florestal.",
	"Deixo-me vencer facilmente numa discussão ou num debate.",
	"Atualmente é-me difícil não perder a esperança de chegar a ser alguém.",
	"Às vezes a minha alma abandona o meu corpo.",
	"Sem dúvida alguma não tenho confiança em mim mesmo/a.",
	"Gostaria de ser florista.",
	"Geralmente sinto que a vida merece ser vivida.",
	"Dá muito trabalho convencer a maioria das pessoas da verdade.",
	"De vez em quando deixo para amanhã o que deveria fazer hoje.",
	"A maior parte das pessoas que me conhecem gostam de mim.",
	"Não me importo que façam troça de mim.",
	"Gostaria de ser enfermeiro/a.",
	"Acho que a maioria das pessoas é capaz de mentir para obter aquilo que quer.",
	"Faço muitas coisas de que logo me arrependo. (Arrependo-me mais dos que os outros parecem fazê-lo)",
	"Tenho muito poucas discussões com as pessoas da minha família.",
	"Fui suspenso da escola uma ou mais vezes por mau comportamento.",
	"Por vezes sinto fortes desejos de fazer algo prejudicial ou chocante.",
	"Gosto de participar em reuniões ou festas onde haja muita animação.",
	"Confrontei-me com problemas que por terem diversas opções de solução me foi impossível chegar a uma decisão.",
	"Acredito que a mulher deve ter tanta liberdade sexual como o homem.",
	"Os conflitos mais graves que tenho são comigo mesmo/a.",
	"Gosto do meu pai (ou se já faleceu) gostava do meu pai.",
	"Raramente ou nunca tenho espasmos ou cãimbras musculares.",
	"Parece que não me importo muito com o que me possa acontecer.",
	"Por vezes fico de mau humor quando não me sinto bem.",
	"Muitas vezes sinto que fiz alguma coisa mal ou errada.",
	"Estou quase sempre feliz.",
	"Vejo à minha volta coisas, animais ou pessoas que os outros não veem.",
	"A minha cabeça e o meu nariz parecem estar congestionados a maior parte do tempo.",
	"Algumas pessoas são tão autoritárias que me apetece fazer o contrário do que me pedem ainda que eu saiba que elas têm razão.",
	"Alguém rogou-me uma praga.",
	"Nunca fiz algo perigoso só pela emoção de o fazer.",
	"Frequentemente tenho a impressão de ter a cabeça apertada à volta.",
	"Às vezes zango-me.",
	"Gosto mais de um jogo ou uma partida quando aposto.",
	"A maioria das pessoas é honesta por ter medo de ser descoberta.",
	"Na escola fui chamado/a ao diretor algumas vezes pelo meu mau comportamento.",
	"A minha maneira de falar é igual ao que sempre foi (nem mais rápida nem mais lenta nem balbuciante nem rouca).",
	"Os meus modos de estar à mesa não são tão corretos em minha casa do que quando como fora.",
	"Qualquer pessoa que seja capaz e esteja disposta a trabalhar arduamente tem muitas probabilidades de ter êxito.",
	"Parece-me que sou tão esperto/a e capaz como a maior parte dos que me rodeiam.",
	"A maioria das pessoas é capaz de utilizar meios pouco honestos para não perder um benefício ou uma vantagem.",
	"Tenho muitos problemas de estômago.",
	"Gosto de teatro.",
	"Sei quem é o responsável pela maioria dos meus problemas.",
	"Por vezes sinto-me tão atraído/a pelas coisas pessoais dos outros (como sapatos, luvas, etc.) que desejaria pegá-los ou roubá-los mesmo que não precise deles.",
	"Quando vejo sangue não tenho medo nem me sinto mal.",
	"Não consigo compreender porque tenho andado frequentemente tão irritável e malhumorado/a.",
	"Nunca vomitei ou cuspi sangue.",
	"Não me preocupa poder contrair doenças.",
	"Gosto de ter flores ou cultivar plantas em casa.",
	"Frequentemente acho que é necessário defender o que é justo.",
	"Nunca me envolvi em práticas sexuais fora do comum.",
	"Às vezes os meus pensamentos andam mais depressa do que as minhas palavras.",
	"Se pudesse entrar num cinema sem pagar e tivesse seguro/a de que não iria ser visto/a provavelmente o faria.",
	"Pergunto-me geralmente que razão oculta poderá ter uma pessoa quando me faz um favor.",
	"Creio que a minha vida familiar é tão agradável como a da maioria das pessoas que conheço.",
	"Acredito na força da lei.",
	"As críticas e as repreensões magoam-me profundamente.",
	"Gosto de cozinhar.",
	"A minha conduta é maioritariamente influenciada pelo comportamento dos que me rodeiam.",
	"Por vezes sinto-me de facto um/a inútil.",
	"Quando era criança pertencia a um grupo de amigos que tentava manter-se unido perante qualquer adversidade.",
	"Acredito que existe outra vida depois desta.",
	"Gostaria de ser militar.",
	"Por vezes sinto desejo de andar aos murros com alguém.",
	"Frequentemente desperdiço ou não aproveito oportunidades porque não me decidi a tempo.",
	"Quando estou a trabalhar em algo importante, fico impaciente se as pessoas me interrompem ou me pedem uma opinião.",
	"Costumava ter um diário.",
	"Acredito que estão a planear algo contra mim.",
	"Num jogo ou numa partida gosto mais de ganhar do que perder.",
	"A maioria das noites adormeço sem pensamentos ou ideias que me aborreçam.",
	"Durante os últimos anos tenho gozado quase sempre de boa saúde.",
	"Nunca sofri um ataque ou convulsões.",
	"Neste momento não estou a ganhar nem a perder peso.",
	"Acho que me estão a perseguir.",
	"Acho que tenho sido muitas vezes castigado/a sem nenhum motivo.",
	"Choro facilmente.",
	"Não consigo compreender tão bem o que leio como antes.",
	"Nunca me senti tão bem na minha vida como agora.",
	"Por vezes sinto a parte superior da cabeça dorida.",
	"Às vezes sinto vontade de fazer mal a mim ou a alguém.",
	"Aborrece-me o facto de alguém se ter aproveitado de mim ao ponto de eu ter reconhecido que o conseguiu.",
	"Não me canso facilmente.",
	"Gosto de conhecer algumas pessoas importantes porque isso faz-me sentir importante.",
	"Tenho medo quando olho para baixo de um lugar alto.",
	"Não ficaria nervoso/a se um familiar meu tivesse problemas com a lei.",
	"Só estou feliz quando ando sem destino ou viajo de um lado para o outro.",
	"Não me preocupo com o que os outros pensam sobre mim.",
	"Sinto-me incomodado/a quando tenho que fazer palhaçada numa festa mesmo que os outros também o façam.",
	"Nunca desmaiei.",
	"Gostava da escola.",
	"Frequentemente tenho que me esforçar para esconder a minha timidez.",
	"Alguém tem tentado envenenar-me.",
	"Não tenho muito medo de cobras.",
	"Nunca ou raramente tenho tonturas.",
	"A minha memória parece estar boa.",
	"Estou preocupado/a com sexo.",
	"Acho difícil iniciar uma conversa com pessoas que acabei de conhecer.",
	"Houve períodos durante os quais realizei atividades que depois não me recordava de as ter feito.",
	"Quando estou aborrecido/a gosto de provocar alguma excitação.",
	"Tenho medo de enlouquecer.",
	"Sou contra dar dinheiro aos mendigos.",
	"Noto frequentemente que as minhas mãos tremem quando tento fazer alguma coisa.",
	"Consigo ler durante muito tempo sem cansar a minha vista.",
	"Gosto de estudar coisas sobre as quais estou a trabalhar.",
	"A maior parte do tempo sinto uma fraqueza geral.",
	"É raro ter dores de cabeça.",
	"As minhas mãos não se tornaram desajeitadas nem perderam a habilidade.",
	"Por vezes quando fico embaraçado/a começo a suar, o que me incomoda imenso.",
	"Não tenho tido dificuldades em manter o equilíbrio quando caminho.",
	"Alguma coisa não funciona bem na minha cabeça.",
	"Não tenho crises de “febre dos fenos” ou de asma.",
	"Já tive ataques durante os quais perdi o controlo dos meus movimentos ou da fala mas sabia o que se estava a passar à minha volta.",
	"Não gosto de todas as pessoas que conheço.",
	"É raro sonhar acordado.",
	"Gostava de não ser tão tímido/a.",
	"Não tenho medo de lidar com o dinheiro.",
	"Se fosse jornalista gostaria muito de fazer reportagens sobre teatro.",
	"Aprecio uma grande variedade de jogos e passatempos.",
	"Gosto de namoriscar.",
	"A minha família trata-me mais como uma criança do que como um adulto.",
	"Gostava de ser jornalista.",
	"A minha mãe é uma boa mulher (ou se já faleceu) a minha mãe foi uma boa mulher.",
	"Quando ando tenho muito cuidado com os buracos do passeio.",
	"Nunca tive erupção na pele que me tivesse preocupado.",
	"Na minha família há pouca união e afeto comparado com outras famílias.",
	"Frequentemente dou comigo preocupado/a com alguma coisa.",
	"Acho que gostaria da profissão de encarregado de obras.",
	"Oiço frequentemente vozes que não sei de onde vêm.",
	"Gosta de ciência.",
	"Não me custa pedir ajuda aos meus amigos mesmo que não possa devolver-lhes o favor.",
	"Gosto muito de caçar.",
	"Os meus pais opuseram-se muitas vezes ao tipo de pessoas com quem me dava.",
	"Às vezes sou um pouco bisbilhoteiro/a.",
	"Aparentemente oiço tão bem como a maioria das pessoas.",
	"Alguns dos meus familiares têm hábitos que me aborrecem e incomodam muitíssimo.",
	"Às vezes sinto que sou capaz de tomar decisões com uma facilidade extraordinária.",
	"Gostaria de pertencer a vários clubes ou associações.",
	"Raramente sinto palpitações no coração ou falta de ar.",
	"Gosto de falar sobre sexo.",
	"Gosto de visitar lugares onde nunca estive.",
	"Fui inspirado/a num estilo de vida baseado no dever o qual tenho seguido cuidadosamente.",
	"Por vezes impedi alguém de fazer alguma coisa não porque fosse importante mas por questão de princípios.",
	"Fico facilmente furioso/a mas passa-me depressa.",
	"Tenho sido bastante livre e independente da disciplina familiar.",
	"Preocupo-me muito com as coisas.",
	"Alguém tentou roubar-me.",
	"Quase todos os meus familiares simpatizam comigo.",
	"Tenho períodos de tanta agitação que não consigo estar muito tempo sentado/a numa cadeira.",
	"Sofri desgostos amorosos.",
	"Nunca me preocupo com a minha aparência física.",
	"Sonho frequentemente com coisas que é melhor guardá-lo para mim.",
	"Deveriam ensinar-se às crianças todos os aspetos principais da vida sexual.",
	"Acho que não sou mais nervoso/a do que a maioria das pessoas.",
	"Tenho poucas ou nenhumas dores.",
	"A minha maneira de fazer as coisas tende a ser mal interpretada pelos outros.",
	"Algumas vezes sem nenhuma razão mesmo quando as coisas correm mal sinto-me extremamente feliz como se \"andasse nas nuvens\"",
	"Não censuro as pessoas que procuram tirar partido de tudo o que podem, neste mundo.",
	"Existem pessoas que tentam roubar os meus pensamentos e as minhas ideias.",
	"Tive momentos de tanta confusão que interrompi as minhas atividades e não sabia o que se passava à minha volta.",
	"Consigo ser amigável com pessoas que fazem coisas que eu considero incorretas.",
	"Gosto de estar em grupos em que as pessoas brincam umas com as outras.",
	"Algumas vezes voto nas eleições em pessoas que não conheço muito bem.",
	"Tenho dificuldade em começar a fazer coisas.",
	"Acredito que sou uma pessoa condenado/a.",
	"Quando andava na escola era lento/a a aprender.",
	"Se fosse artista gostaria de desenhar flores.",
	"Não me preocupa o facto de não ter uma melhor aparência física.",
	"Transpiro muito facilmente mesmo nos dias frios.",
	"Sou uma pessoa plenamente segura de mim mesma.",
	"Algumas vezes não consegui evitar roubar algo ou levar alguma coisa de uma loja.",
	"É mais seguro não confiar em ninguém.",
	"Fico muito agitado/a uma vez por semana ou até com mais frequência.",
	"Quando estou com um grupo de pessoas tenho dificuldade em pensar em temas adequados para falar.",
	"Quando me sinto abatido/a alguma coisa emocionante me tira quase sempre desse estado.",
	"Quando saio de casa não me preocupo se a porta ou as janelas ficaram bem fechadas.",
	"Acredito que os meus pecados são imperdoáveis.",
	"Tenho uma ou mais partes da minha pele dormentes.",
	"Não censuro uma pessoa que se aproveita de outra se essa outra deixar.",
	"A minha vista está tão boa agora como sempre esteve.",
	"Às vezes diverte-me tanto uma habilidade de um patife que chego a desejar que não seja apanhado.",
	"Frequentemente tenho a sensação de que desconhecidos olham para mim de uma forma crítica.",
	"Tudo tem o mesmo sabor.",
	"Bebo uma quantidade excessiva de água todos os dias.",
	"A maior parte das pessoas faz amigos porque é provável que lhes venham a ser úteis.",
	"É raro sentir zumbidos ou assobios nos ouvidos.",
	"Por vezes sinto ódio de familiares de quem normalmente gosto.",
	"Se fosse jornalista gostava muito de fazer reportagens sobre desporto.",
	"Consigo dormir durante o dia mas não à noite.",
	"Tenho a certeza de que as pessoas falam de mim.",
	"De vez em quando as piadas ordinárias divertem-me.",
	"Tenho muito poucos medos comparado com os meus amigos.",
	"Não sentiria qualquer vergonha se estivesse num grupo e me pedissem para começar um debate ou dar a minha opinião acerca de algo que conheço bem.",
	"Sinto-me sempre desgostoso/a com a justiça quando um criminoso sai em liberdade graças aos argumentos de um advogado astuto.",
	"Tenho abusado das bebidas alcoólicas.",
	"Geralmente não falo às pessoas a não ser que elas me falem primeiro.",
	"Nunca tive problemas com a lei.",
	"Tenho alturas em que me sinto mais animado/a sem nenhuma razão especial.",
	"Gostaria de não ser incomodado/a por pensamentos de ordem sexual.",
	"Se várias pessoas se encontram metidas num sarilho, o melhor que têm a fazer é concordarem numa história e agarrarem-se a ela.",
	"Não me incomoda particularmente ver os animais a sofrer.",
	"Acho que sinto as coisas mais intensamente do que a maioria das pessoas.",
	"Em nenhum período da minha vida gostei de brincar com bonecas.",
	"Com frequência a vida é-me difícil.",
	"Sou tão sensível em relação a alguns temas que nem sequer posso falar neles.",
	"Na escola custava-me muito falar perante a turma.",
	"Gosto da minha mãe (ou se já faleceu) gostei da minha mãe.",
	"Mesmo quando estou com pessoas sinto-me sozinho/a a maior parte do tempo.",
	"Tenho toda a compreensão que deveria receber.",
	"Recuso-me a participar em alguns jogos porque não sou bom/a neles.",
	"Parece-me que faço amigos tão facilmente como os outros.",
	"Não gosto de ter gente à minha volta.",
	"Disseram-me que ando enquanto estou a dormir.",
	"Quem provoca a tentação deixando uma coisa valiosa sem a proteger, é tão culpado do roubo como o próprio ladrão.",
	"Penso que quase toda a gente mentiria, para evitar problemas.",
	"Sou mais sensível que a maioria das pessoas.",
	"No fundo, a maior parte das pessoas não gosta de se incomodar para ajudar os outros.",
	"Muitos dos meus sonhos estão relacionados com sexo.",
	"Os meus pais e a minha família encontram em mim mais defeitos do que deviam.",
	"Facilmente me sinto envergonhado/a.",
	"Preocupo-me com o dinheiro e os negócios.",
	"Nunca estive apaixonado/a por ninguém.",
	"Algumas pessoas da minha família fizeram coisas que me assustaram.",
	"Quase nunca sonho.",
	"Aparecem-me com frequência manchas vermelhas no pescoço.",
	"Nunca fiquei paralisado nem tive qualquer debilidade invulgar de natureza muscular.",
	"Algumas vezes fico sem voz ou a minha voz altera-se mesmo não estando constipado/a.",
	"Frequentemente a minha mãe ou o meu pai obrigaram-me a obedecer mesmo quando eu pensava que não tinham razão.",
	"Às vezes sinto cheiros estranhos.",
	"Não consigo concentrar-me numa só coisa.",
	"Tenho motivos para sentir ciúmes de um ou mais membros da minha família.",
	"A maior parte do tempo sinto-me ansioso/a com alguma coisa ou com alguém.",
	"Facilmente perco a paciência com as pessoas.",
	"Na maior parte do tempo desejaria estar morto/a.",
	"Algumas vezes, sinto-me tão inquieto/a que me custa adormecer à noite.",
	"Sem dúvida, tive que me preocupar com mais coisas do que as que me diziam respeito.",
	"Ninguém se preocupa o suficiente com o que acontece comigo.",
	"Às vezes, oiço tão bem que me chega a incomodar.",
	"Esqueço logo aquilo que me dizem.",
	"Normalmente, tenho que pensar primeiro antes de agir, mesmo em assuntos pouco importantes.",
	"Frequentemente atravesso a rua para evitar encontrar-me com alguma pessoa.",
	"Frequentemente sinto as coisas como se não fossem reais.",
	"A única parte interessante dos jornais são as caricaturas da secção cómica.",
	"Tenho o costume de contar as coisas sem importância, como as letras de um anúncio de rua ou outras semelhantes.",
	"Não tenho inimigos que desejem realmente fazer-me mal.",
	"Tenho tendência a acautelar-me com as pessoas que são mais amigáveis comigo do que esperava.",
	"Tenho pensamentos estranhos e raros.",
	"Fico nervoso/a e inquieto/a quando tenho que fazer uma pequena viagem.",
	"Normalmente espero ter êxito nas coisas que faço.",
	"Oiço coisas estranhas quando estou sozinho/a.",
	"Tive medo de coisas ou pessoas que eu sabia que não me podiam fazer mal.",
	"Não tenho receio de entrar sozinho/a numa sala onde outras pessoas já estão reunidas a conversar.",
	"Tenho medo de utilizar facas ou objetos muito afiados e pontiagudos.",
	"Por vezes, gosto de magoar as pessoas que amo.",
	"Facilmente consigo que as pessoas tenham medo de mim e, às vezes faço-o por divertimento.",
	"Para mim é mais difícil concentrar-me do que parece ser para as outras pessoas.",
	"Houve várias ocasiões em que desisti de fazer algo, porque duvidei das minhas capacidades.",
	"Quando me vêm à minha cabeça palavrões ou palavras terríveis não consigo libertar-me deles/as.",
	"Por vezes sinto que um pensamento sem importância anda às voltas na minha cabeça atormentando-me durante dias.",
	"Quase todos os dias, acontece alguma coisa que me assusta.",
	"Às vezes estou cheio/a de energia.",
	"Tenho tendência a levar as coisas muito a sério.",
	"Por vezes tive ocasiões em que senti prazer em ser magoado/a por uma pessoa de quem gostei muito.",
	"As pessoas insultam-me e dizem coisas ordinárias a meu respeito.",
	"Sinto-me aflito/a em lugares fechados.",
	"Não sou invulgarmente auto-consciente.",
	"Alguém controla a minha mente.",
	"Numa festa é mais provável que me sente sozinho/a ou só com uma outra pessoa do que me junte ao grande grupo.",
	"As pessoas desapontam-me frequentemente.",
	"Por vezes tenho sentido que as dificuldades me sobrecarregam de tal modo que não consigo superá-las",
	"Gosto muito de ir dançar.",
	"Há alturas em que a minha mente parece funcionar mais lentamente que o costume.",
	"Quando viajo falo frequentemente com pessoas que não conheço.",
	"Gosto de crianças.",
	"Gosto de apostar quando se trata de pouco dinheiro.",
	"Se me dessem oportunidade poderia fazer coisas que beneficiariam muito a humanidade.",
	"Tenho encontrado frequentemente pessoas supostamente mais experientes, mas que não se mostraram melhores do que eu.",
	"Sinto-me um/a fracassado/a quando me falam do sucesso de alguém que conheço bem.",
	"Penso com frequência: \"Gostava de voltar a ser criança\".",
	"Nunca sou tão feliz, como quando estou sozinho/a.",
	"Se me dessem oportunidade, poderia ser um bom/boa líder.",
	"Sinto-me incomodado/a quando oiço anedotas ordinárias.",
	"Normalmente as pessoas exigem mais respeito para os seus próprios direitos do que aqueles que estão dispostas a ceder aos outros.",
	"Gosto de reuniões sociais pelo simples facto de estar com pessoas.",
	"Tento recordar histórias interessantes para poder contá-las aos outros.",
	"Uma ou mais vezes, na minha vida senti que por hipnotismo alguém me obrigava a fazer algo.",
	"Custa-me bastante interromper, ainda que seja por pouco tempo, uma tarefa que já tinha iniciado.",
	"Normalmente não participo nos mexericos e boatos do grupo a que pertenço.",
	"Encontro com frequência pessoas com inveja das minhas boas ideias simplesmente porque não lhes ocorreram primeiro.",
	"Gosto da animação de uma multidão.",
	"Não me importo de encontrar pessoas desconhecidas.",
	"Alguém tem tentado influenciar a minha mente.",
	"Lembro-me de ter fingido estar doente para evitar alguma coisa.",
	"As minhas preocupações parecem desaparecer quando estou num grupo de amigos.",
	" Quando as coisas correm mal facilmente me dou por vencido/a.",
	"Gosto que as pessoas conheçam o meu ponto de vista sobre as coisas.",
	"Tive alturas em que me sentia tão animado/a que parecia que durante dias não precisava dormir.",
	"Sempre que possível evito estar no meio de muita gente.",
	"Evito enfrentar uma crise ou dificuldades.",
	"Tenho tendência a deixar de fazer coisas que desejo quando os outros pensam que não vale a pena fazê-lo.",
	"Gosto de festas e reuniões sociais.",
	"Frequentemente desejei pertencer ao sexo oposto.",
	"Não me zango facilmente.",
	"No passado fiz coisas erradas que nunca contei a ninguém.",
	"A maioria das pessoas utilizaria meios pouco honestos para subir na vida.",
	"Sinto-me nervoso/a quando as pessoas me fazem perguntas pessoais.",
	"Sinto que não posso planificar o meu próprio futuro.",
	"Não estou satisfeito/a com a minha maneira de ser.",
	"Zango-me quando os meus amigos ou familiares me dizem como devo viver a minha vida.",
	"Bateram-me muito quando era criança.",
	"Sinto-me incomodado/a quando as pessoas me elogiam.",
	"Não gosto de ouvir outras pessoas a dar as suas opiniões sobre a vida.",
	"Com frequência discordo profundamente das pessoas que me são próximas.",
	"Quando as coisas estão realmente mal, sei que posso contar com a ajuda da minha família.",
	"Quando era pequeno/a gostava de brincar às \"casinhas\".",
	"Não tenho medo do fogo.",
	"Houve ocasiões em que me afastei de pessoas porque tive medo de fazer ou de dizer alguma coisa de que logo me viesse a arrepender.",
	"Só quando bebo é que consigo expressar os meus verdadeiros sentimentos.",
	"Muito raramente tenho momentos de desânimo.",
	"Dizem-me frequentemente que tenho mau feitio.",
	"Queria poder esquecer-me de coisas que disse e que talvez possam ter ferido os sentimentos de outras pessoas.",
	"Sinto-me incapaz de contar a alguém tudo a meu respeito.",
	"Os relâmpagos são um dos meus medos.",
	"Gosto de deixar os outros curiosos com o que vou fazer a seguir.",
	"Encontro frequentemente tantas dificuldades nos meus planos que tenho que os abandonar.",
	"Tenho medo de estar sozinho/a no escuro.",
	"Houve alturas em que me senti muito mal por não ter sido compreendido/a quando tentava evitar que alguém cometesse um erro.",
	"Tenho pavor dos temporais com vento muito forte.",
	"Peço frequentemente conselhos aos outros.",
	"O futuro é demasiado incerto para que uma pessoa faça planos importantes.",
	"Com frequência mesmo quando tudo me está a correr bem, sinto que nada me importa.",
	"Não tenho medo da água.",
	"Com frequência tenho que \"consultar a almofada\" antes de tomar uma decisão.",
	"Frequentemente, as pessoas interpretam mal as minhas intenções quando procuro corrigi-las ou ajudá-las.",
	"Não tenho dificuldades em engolir.",
	"Normalmente sou uma pessoa calma e não me altero facilmente.",
	"Seguramente gostaria de vencer uma pessoa manhosa recorrendo às mesmas armas que ela utiliza.",
	"Mereço ser rigorosamente castigado/a.",
	"As desilusões afetam-me tanto que não posso deixar de pensar nelas.",
	"Incomoda-me que me observem quando estou a trabalhar, mesmo que saiba que o posso fazer bem.",
	"Frequentemente chateia-me tanto que se ponham à minha frente numa fila, que não consigo evitar de chamar à atenção.",
	"Às vezes penso que não valho nada.",
	"Quando era miúdo/a frequentemente não ia à escola mesmo quando devia ir.",
	"Um ou mais dos meus familiares são muito nervosos.",
	"Por vezes tive que ser duro/a com as pessoas mal-educadas ou desagradáveis.",
	"Preocupo-me bastante com possíveis desgraças.",
	"Tenho opiniões políticas bem definidas.",
	"Gostaria de ser piloto de automóveis de competição.",
	"É correto contornar os limites da lei desde que na realidade não a violemos.",
	"Desagradam-me tanto algumas pessoas que fico interiormente satisfeito quando sofrem as consequências do que fizeram.",
	"Ter de esperar deixa-me nervoso/a.",
	"Tenho tendência a deixar de fazer alguma coisa que desejo quando os outros pensam que essa não é a melhor maneira de o fazer.",
	"Quando era mais jovem adorava tudo o que era emocionante.",
	"Frequentemente esforço-me por vencer alguém que me enfrenta.",
	"Incomoda-me que as pessoas olhem para mim na rua, nos transportes, nas lojas, etc.",
	"O homem que mais cuidou de mim quando eu era criança (o meu pai, o meu padrasto, etc.) foi muito rígido comigo.",
	"Gosto de jogar “à macaca” (apanhar uma pedra no chão ao pé coxinho) e saltar à corda.",
	"Nunca tive visões.",
	"Mudei várias vezes a minha forma de sentir em relação ao meu trabalho.",
	"A não ser por receita médica, nunca tomo drogas ou comprimidos para dormir.",
	"Frequentemente lamento ter tão mau feitio ou ser tão resmungão / ona.",
	"Na escola as minhas notas de comportamento foram geralmente más.",
	"O fogo fascina-me.",
	"Quando estou numa situação difícil, digo apenas a parte da verdade que provavelmente não me vai prejudicar.",
	"Se estiver em dificuldades com amigos que são tão culpados como eu, prefiro ficar com a culpa toda em vez de os acusar.",
	"Frequentemente tenho medo do escuro.",
	"Quando um homem está com uma mulher pensa, geralmente, em coisas relacionadas com sexo.",
	"Geralmente \"sou muito direto/a\" a falar com as pessoas que tento corrigir ou melhorar.",
	"Aterroriza-me a ideia de um terramoto.",
	"Rapidamente convencem-me totalmente de uma boa ideia.",
	"Geralmente faço as coisas por mim mesmo/a, em vez de procurar alguém que me diga como fazê-las.",
	"Tenho medo de estar num lugar pequeno ou fechado.",
	"Tenho que admitir que por vezes me preocupo demasiado com algo sem importância.",
	"Não procuro disfarçar ou esconder a pena ou a fraca opinião que tenho de uma pessoa, ao ponto de ela desconhecer o que eu sinto.",
	"Sou uma pessoa muito nervosa.",
	"Trabalhei, frequentemente, sob ordens de pessoas que pareciam organizar as coisas de maneira a terem o reconhecimento de um bom trabalho, mas que em contrapartida eram capazes de atribuir os seus erros aos empregados.",
	"Por vezes é-me difícil defender os meus direitos por ser tão calado/a.",
	"A sujidade apavora-me ou enoja-me.",
	"Vivo uma vida de sonhos, da qual não revelo nada a ninguém.",
	"Alguns dos meus familiares \"fervem em pouca água\".",
	"Não consigo fazer nada bem feito.",
	"Frequentemente sinto-me culpado/a por fingir sofrer mais do que aquilo que realmente sinto.",
	"Como regra defendo fortemente as minhas opiniões.",
	"Não tenho medo de aranhas.",
	"Não tenho esperança no meu futuro.",
	"Os meus familiares mais próximos dão-se muito bem.",
	"Gosto de vestir roupa cara.",
	"As pessoas podem fazer-me mudar de opinião facilmente mesmo nos assuntos em que penso ter uma ideia bem definida.",
	"Alguns animais deixam-me nervoso/a.",
	"Consigo suportar a dor, tanto como as outras pessoas.",
	"Por diversas vezes, fui o/a último/a a dar-me por vencido/a ao tentar fazer alguma coisa.",
	"Irrito-me quando os outros me apressam.",
	"Não tenho medo de ratos.",
	"Várias vezes por semana sinto que vai acontecer algo terrível.",
	"Sinto-me cansado/a a maior parte do tempo.",
	"Gosto de consertar as fechaduras das portas.",
	"Algumas vezes tenho a certeza de que os outros podem saber o que estou a pensar.",
	"Gosto de ler sobre temas científicos.",
	"Tenho medo de estar sozinho/a em lugares amplos e abertos.",
	"Às vezes sinto que estou à beira de um \"ataque de nervos\".",
	"Um grande número de pessoas é culpado de um mau comportamento sexual.",
	"Frequentemente sinto medo a meio da noite.",
	"Aborrece-me muito esquecer onde ponho as coisas.",
	"A pessoa por quem senti mais afeto e admiração quando era pequeno/a, foi uma mulher (mãe, irmã, tia ou outra mulher).",
	"Gosto mais de histórias de aventuras do que românticas.",
	"Frequentemente sinto-me confuso/a e esqueço-me do que quero dizer.",
	"Sou muito desajeitado/a e pouco desembaraçado/a.",
	"Gosto, realmente, de jogar desportos violentos (como o rugby e o futebol).",
	"Odeio toda a minha família.",
	"Algumas pessoas pensam que é difícil chegar a conhecer-me.",
	"Passo sozinho/a a maior parte do meu tempo livre.",
	"Quando alguém faz alguma coisa que me irrita, faço com que o saiba.",
	"Frequentemente custa-me decidir o que devo fazer.",
	"As pessoas não me consideram atraente.",
	"As pessoas não se mostram muito amáveis comigo.",
	"Sinto com frequência que não sou tão bom/boa como as outras pessoas.",
	"Sou muito teimoso/a (decidido/a, insistente).",
	"Gostei de consumir drogas.",
	"A doença mental é um sinal de debilidade.",
	"Tenho problemas com as drogas e com o álcool.",
	"Os fantasmas e os espíritos podem influenciar as pessoas para o bem e para o mal.",
	"Sinto-me incapaz quando tenho que tomar uma decisão importante.",
	"Procuro sempre ser amável mesmo quando os outros se mostram aborrecidos e críticos.",
	"Quando tenho algum problema alivia-me poder falar com alguém.",
	"Os objetivos mais importantes da minha vida estão ao meu alcance.",
	"Acho que as pessoas deveriam guardar para si os seus problemas pessoais.",
	"Nos últimos dias não tenho sentido muita pressão ou stresse.",
	"Aborrece-me muito pensar em fazer mudanças na minha vida.",
	"Os meus maiores problemas devem-se ao comportamento de alguém que está próximo de mim.",
	"Detesto ir ao médico mesmo quando estou doente.",
	"Mesmo não estando contente com a minha vida já não posso fazer nada para a mudar.",
	"Frequentemente é mais proveitoso falar dos problemas e preocupações com alguém do que tomar calmantes e medicamentos.",
	"Tenho alguns hábitos que realmente me fazem mal.",
	"Quando é preciso resolver problemas habitualmente deixo que os outros os resolvam.",
	"Reconheço que tenho alguns defeitos que não serei capaz de mudar.",
	"Estou tão farto/a das coisas que tenho que fazer diariamente que tenho vontade de abandonar tudo.",
	"Recentemente pensei em matar-me.",
	"Frequentemente irrito-me muito quando as pessoas interrompem o meu trabalho.",
	"Sinto com frequência que posso ler a mente dos outros.",
	"Fico nervoso/a ao ter que tomar decisões importantes.",
	"Dizem que como demasiado rápido.",
	"Uma vez por semana ou com mais frequência costumo embebedar-me ou drogar-me.",
	"Sofri uma perda importante na minha vida que não vou poder ultrapassar.",
	"Às vezes aborreço-me e altero-me tanto que não sei o que se passa comigo.",
	"Quando alguém me pede para fazer alguma coisa custa-me dizer que não.",
	"Nunca me sinto tão feliz como quando estou sozinho/a.",
	"A minha vida está vazia e não tem sentido.",
	"Tenho dificuldade em manter um trabalho.",
	"Cometi bastantes erros graves na minha vida.",
	"Chateio-me comigo mesmo/a quando cedo perante os outros.",
	"Ultimamente tenho pensado muito em suicidar-me.",
	"Gosto de tomar decisões e de organizar o trabalho dos outros.",
	"Mesmo que me falte a família sei que haverá sempre alguém que cuide de mim.",
	"Detesto ficar na fila para os cinemas, restaurantes ou espetáculos desportivos.",
	"Ninguém sabe, mas tentei suicidar-me.",
	"Está tudo a acontecer muito rápido à minha volta.",
	"Sei que sou um peso para os outros.",
	"Depois de um mau dia, geralmente preciso beber \"uns copos\" para me relaxar.",
	"Muitos dos problemas que tenho tido devem-se ao azar.",
	"Às vezes parece que não consigo deixar de falar.",
	"Em algumas ocasiões corto-me ou firo-me de propósito, sem saber porquê.",
	"Trabalho muitas horas mesmo que o meu trabalho não o exija.",
	"Habitualmente sinto-me melhor depois de chorar bastante.",
	"Esqueço-me onde deixo as coisas.",
	"Se pudesse começar a minha vida de novo não a mudaria muito.",
	"Irrito-me muito quando as pessoas das quais dependo para trabalhar não fazem o seu trabalho a tempo.",
	"Se me zango tenho a certeza que me vai doer a cabeça.",
	"Gosto de negociar em situações difíceis.",
	"A maioria dos maridos é infiel às suas esposas de vez em quando.",
	"Ultimamente perdi o interesse em resolver os meus próprios problemas.",
	"Sob o efeito de álcool enfureci-me e destruí móveis ou loiça.",
	"Trabalho melhor quando tenho um prazo fixo para cumprir.",
	"Zanguei-me tanto com uma pessoa que estive perto de explodir.",
	"Por vezes tenho pensamentos terríveis sobre a minha família.",
	"As pessoas dizem-me que tenho problemas com o álcool, mas eu não concordo.",
	"Tenho sempre muito pouco tempo para fazer as coisas.",
	"Ultimamente os meus pensamentos centram-se, cada vez mais, na morte e na vida do além.",
	"Com frequência, guardo e conservo coisas que provavelmente nunca usarei.",
	"Algumas vezes zanguei-me tanto com uma pessoa que cheguei a magoá-la fisicamente.",
	"Em tudo o que tenho feito ultimamente sinto que estou a ser testado/a.",
	"Atualmente relaciono-me pouco com os meus familiares.",
	"Em certas ocasiões parece que oiço os meus próprios pensamentos em voz alta.",
	"Quando estou triste, visitar os meus amigos consegue tirar-me desse estado.",
	"Muitas das coisas que estão a acontecer-me agora, parece que já me aconteceram antes.",
	"Quando a minha vida se complica tenho vontade de deixar tudo.",
	"Não consigo entrar sozinho/a num quarto escuro mesmo na minha própria casa.",
	"Preocupa-me bastante o dinheiro.",
	"O homem deveria ser o chefe da família.",
	"O único lugar onde me sinto relaxado é na minha própria casa.",
	"As pessoas com quem trabalho não compreendem os meus problemas.",
	"Estou satisfeito/a com o montante de dinheiro que ganho.",
	"Normalmente tenho energia suficiente para realizar o meu trabalho.",
	"Custa-me aceitar elogios.",
	"Na maioria dos casamentos um ou ambos os cônjuges são infelizes.",
	"Quase nunca perco o controlo de mim mesmo/a.",
	"Ultimamente tenho que fazer um grande esforço para me lembrar do que as pessoas me disseram.",
	"Quando estou triste e abatido/a, geralmente é o meu trabalho que sai prejudicado.",
	"A maioria dos casais que estão casados não demonstra muito afeto um pelo outro."
];